# Generated by Django 2.2.24 on 2023-04-03 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0007_auto_20230403_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='complaint',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_flats', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
