# Generated by Django 2.2.24 on 2023-04-03 11:12

from django.db import migrations
import phonenumbers

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_flat_owner_pure_phone'),
    ]

    def parse_phonenumbers(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        for flat in Flat.objects.all().iterator():
            flat.owner_pure_phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
            flat.save()

    operations = [
        migrations.RunPython(parse_phonenumbers)
    ]
