# Generated by Django 2.2.24 on 2023-04-03 12:50

from django.db import migrations


def migrate_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flats in Flat.objects.all().iterator():
        Owner.objects.get_or_create(
            owners=Flat.owner,
            owners_phonenumber=Flat.owners_phonenumber,
            owner_pure_phone=Flat.owner_pure_phone,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0013_auto_20230403_1550'),
    ]


    operations = [
        migrations.RunPython(migrate_owners)
    ]
