# Generated by Django 2.2.24 on 2023-04-03 13:42

from django.db import migrations


def migrate_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all().iterator():
        Owner.objects.get_or_create(
            flat_owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone, )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20230403_1633'),
    ]


    operations = [
        migrations.RunPython(migrate_owners)
    ]
