# Generated by Django 2.2.24 on 2023-04-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_auto_20230404_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='flat',
            new_name='flats',
        ),
    ]
